[[tree_sitter_c_sharp]]
arch = "aarch64"
git-tree-sha1 = "90cb3cdd06589fbacb87f83bbb09327c0e3c9f64"
os = "macos"

    [[tree_sitter_c_sharp.download]]
    sha256 = "b77fcfde5069f894b3a45c27c66d693deb6e278ee9b106e4e81411429ef2912f"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.aarch64-apple-darwin.tar.gz"
[[tree_sitter_c_sharp]]
arch = "aarch64"
git-tree-sha1 = "8d2bc0ff6d6b61020114e940ecfaf0d68011ca50"
libc = "glibc"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "72e387f3eff10f04de89797364433e25a1bd73fe3ee6e33b065e76799a898546"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.aarch64-linux-gnu.tar.gz"
[[tree_sitter_c_sharp]]
arch = "aarch64"
git-tree-sha1 = "3e31da418cd172f0088d2b7debfbba30ac1dc0fa"
libc = "musl"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "0e06d3a28b1cf7a440c3e55ec52de2e90988da16c31ea0b955e1169a9e442870"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.aarch64-linux-musl.tar.gz"
[[tree_sitter_c_sharp]]
arch = "aarch64"
git-tree-sha1 = "bf38f9f3f695fb0caef5346235e702a6fbb8d2c7"
os = "freebsd"

    [[tree_sitter_c_sharp.download]]
    sha256 = "9a0f7e072e54e8cb15fcaa5ccda894d4aa7e97c5ff85d1b708e3863e5de2702e"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.aarch64-unknown-freebsd.tar.gz"
[[tree_sitter_c_sharp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dfd36d51f9f035532e07932f759b98d96c40357d"
libc = "glibc"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "fd9787441b284d21cf539adb050c25a959180de733ebc63363d42c8158068b49"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.armv6l-linux-gnueabihf.tar.gz"
[[tree_sitter_c_sharp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "23d49aaba5cc26716f35b75da4c123c0ae00e788"
libc = "musl"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "652fe3d6b295db02fd713416844a9ae96c6b85427121d9ab33f0743b43c0444d"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.armv6l-linux-musleabihf.tar.gz"
[[tree_sitter_c_sharp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "91b94ae00348296560b3b29a01bb91fac514e4b0"
libc = "glibc"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "588a895ca9ac208dba48b952f3c5006dba8e293e3ee1e45d24a7c780f097d6e8"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.armv7l-linux-gnueabihf.tar.gz"
[[tree_sitter_c_sharp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c25fb5f4644e4a9751a9f72cd0498ea7e9e48e92"
libc = "musl"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "5a4062fc5f9129419ff58d49033fd4a5ad16c19ea45b56d9ead676294d4039bf"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.armv7l-linux-musleabihf.tar.gz"
[[tree_sitter_c_sharp]]
arch = "i686"
git-tree-sha1 = "a3c08f42a69d9f0440412898acffc54c65d00c0a"
libc = "glibc"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "4c13f6d314742543ce9a91324ff888cfb46fb308fa094c0f317a78c7bb4404bd"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.i686-linux-gnu.tar.gz"
[[tree_sitter_c_sharp]]
arch = "i686"
git-tree-sha1 = "f0f3ddd18bb3ca4e13a8ff7240ec20f446895003"
libc = "musl"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "182ca7b3c94b0b9bfde63a25f7459cdf6eed729e05a376d3a10523c1be4ccf45"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.i686-linux-musl.tar.gz"
[[tree_sitter_c_sharp]]
arch = "i686"
git-tree-sha1 = "1e06789684c12ca4d735d20b2fdb89cc8f7b6d53"
os = "windows"

    [[tree_sitter_c_sharp.download]]
    sha256 = "270037e7ca9241d44262471165f6b043740542342c4d95603db0311f7a20d74a"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.i686-w64-mingw32.tar.gz"
[[tree_sitter_c_sharp]]
arch = "powerpc64le"
git-tree-sha1 = "8017a9c40f02389c8ec79ce3df74790ff5de4ccd"
libc = "glibc"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "4d3e2a37059df73f5c80282546c15a3aac12c52c67d33e12593fad3f46d9a76b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.powerpc64le-linux-gnu.tar.gz"
[[tree_sitter_c_sharp]]
arch = "riscv64"
git-tree-sha1 = "3cbe85b1c43014f22ad1211188d1578a567a1cb5"
libc = "glibc"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "bc74ec23f84f4c487f550603c25e4fc96b3594d2e9d167f8b422746be699e3ab"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.riscv64-linux-gnu.tar.gz"
[[tree_sitter_c_sharp]]
arch = "x86_64"
git-tree-sha1 = "eb434ed0651e8965c6af2aab0aa9ceaf9cd1524f"
os = "macos"

    [[tree_sitter_c_sharp.download]]
    sha256 = "2a6207e28e22030b8ce86b928b972fd967892915c3a9b5a764bb3c242708cc9b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.x86_64-apple-darwin.tar.gz"
[[tree_sitter_c_sharp]]
arch = "x86_64"
git-tree-sha1 = "42ea0208e76fa8933e0362225b70ce3a9e740fa2"
libc = "glibc"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "48a3b47385ed2e98081fe0b88960319f55c73730a9b76bddc9c794a22c4003c0"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.x86_64-linux-gnu.tar.gz"
[[tree_sitter_c_sharp]]
arch = "x86_64"
git-tree-sha1 = "fc62f1e2a352ea70d86187664a3ddce1b4242af5"
libc = "musl"
os = "linux"

    [[tree_sitter_c_sharp.download]]
    sha256 = "79da037ffece376b371ebab72b2aa6da7afefff52f32d014583847d5b9cbc769"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.x86_64-linux-musl.tar.gz"
[[tree_sitter_c_sharp]]
arch = "x86_64"
git-tree-sha1 = "4c6230568bc0423444d9f41c6bc7e16e90be0e35"
os = "freebsd"

    [[tree_sitter_c_sharp.download]]
    sha256 = "5f34f8572533b6469e158fe7b6f365f935dee5ae664d2615ece94dfb73a1e723"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.x86_64-unknown-freebsd.tar.gz"
[[tree_sitter_c_sharp]]
arch = "x86_64"
git-tree-sha1 = "4ba312e679d01040bf4315d202b68c790077a833"
os = "windows"

    [[tree_sitter_c_sharp.download]]
    sha256 = "a1fd4062c100719f6cdde3b81f27881c0329a9ef989cb234ddf60766cb95d345"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_sharp_jll.jl/releases/download/tree_sitter_c_sharp-v0.23.1+0/tree_sitter_c_sharp.v0.23.1.x86_64-w64-mingw32.tar.gz"
