# Autogenerated wrapper script for tree_sitter_c_sharp_jll for aarch64-apple-darwin
export libtreesitter_c_sharp

JLLWrappers.@generate_wrapper_header("tree_sitter_c_sharp")
JLLWrappers.@declare_library_product(libtreesitter_c_sharp, "@rpath/libtreesitter_c_sharp.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_c_sharp,
        "lib/libtreesitter_c_sharp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
