# Autogenerated wrapper script for tree_sitter_c_sharp_jll for i686-w64-mingw32
export libtreesitter_c_sharp

JLLWrappers.@generate_wrapper_header("tree_sitter_c_sharp")
JLLWrappers.@declare_library_product(libtreesitter_c_sharp, "libtreesitter_c_sharp.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_c_sharp,
        "bin\\libtreesitter_c_sharp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
