# Autogenerated wrapper script for tree_sitter_c_sharp_jll for x86_64-unknown-freebsd
export libtreesitter_c_sharp

JLLWrappers.@generate_wrapper_header("tree_sitter_c_sharp")
JLLWrappers.@declare_library_product(libtreesitter_c_sharp, "libtreesitter_c_sharp.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_c_sharp,
        "lib/libtreesitter_c_sharp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
